version: '2'

services:
  IdentityServer-ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0-buster
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./netcore-docker.csproj && dotnet publish ./netcore-docker.csproj -c Release -o ./obj/Docker/publish"